// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"
	"go-zero-demo/mall/user/rpc/userclient"

	"go-zero-demo/mall/user/rpc/internal/logic"
	"go-zero-demo/mall/user/rpc/internal/svc"
	"go-zero-demo/mall/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *userclient.IdRequest) (*userclient.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
